### ISSUE TITLE
Player can win after dying if they wait until end of game

### ISSUE THREAD

**Issue by jameshallam93** [Jameskmonger/creature-chess#382]
Even if the player has died, they are able to win the game by simply staying in the lobby until there is only one other Bot left (not tested with other users).
![winwhendead](https://user-images.githubusercontent.com/63243789/114910833-42ac7680-9e16-11eb-93d8-83bcd178043e.png)

**Comment by Jameskmonger** [comment]
I'm pretty sure this comes from here: https://github.com/Jameskmonger/creature-chess/blob/master/packages/gamemode/src/game/gameLoop/index.ts#L18

`players` is the list of all players, so I think that at the moment, the first player in the lobby always wins 😱

`players` doesn't get sorted based on health etc, that's all handled in `playerList`
