### ISSUE TITLE
Reconnect overlay not working properly

### ISSUE THREAD

**Issue by jameshallam93** [Jameskmonger/creature-chess#449]
If a player refreshes the page during a game, and then reconnects, the reconnect overlay doesn't change the player status from 0 to 1. This stops the card shop from refreshing, and interferes with overlays being displayed properly. Their level is also reset to 1, their money is reset to $3, and won't update in line with what's displayed in the playerList.
![shopbug3](https://user-images.githubusercontent.com/63243789/127150609-0bc8afec-1c70-466b-b35b-31dcea63c222.jpg)

**Comment by jameshallam93** [comment]
Digging a bit deeper, it's probably nothing to do with the reconnect overlay, more likely to be in `matchmaking/lobby`

**Comment by Jameskmonger** [comment]
closing as no longer an issue (I think) please feel free to reopen if you notice it again
